Controllers/BookingsController.cs
using Application;
using Application.Services;
using Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HotelManagement1.Controllers
{
    public class BookingsController : Controller
    {
        private RoomService rs = new RoomService();

        // GET: Bookings
        public ActionResult Index()
        {
            //var roomList = uow.UserRepository.GetByID((int)Session["userID"]);
            return View(rs.GetRoomsByUserId((int)Session["userID"]));
        }
        [HttpGet]
        public ActionResult Checkout(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = rs.GetRoomByID(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            // ViewBag.UserId = new SelectList(uow.UserRepository.GetAll(), "UserId", "Name", room.UserId);
            return View(room);
        }
        [HttpPost]
        public ActionResult Checkout([Bind(Include = "Id,Name,Price,IsOccupied,CheckInDate,CheckOutDate,UserId")] Room room)
        {
            if (ModelState.IsValid)
            {
                room.IsOccupied = false;
                room.UserId = null;
                room.CheckInDate = null;
                room.CheckOutDate = null;                
                rs.UpdateRoom(room);
                return RedirectToAction("Index");
            }
            //ViewBag.UserId = new SelectList(db.UserList, "UserId", "Name", room.UserId);
            return View(room);
        }
    }
}

Controllers/RoomSelectController.cs
using Application;
using Application.Services;
using Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HotelManagement1.Controllers
{
    public class RoomSelectController : Controller
    {
        private RoomService rs = new RoomService();
        
        // GET: RoomSelect
        public ActionResult Index()
        {
            return View(rs.GetAllRooms());
        }
        [HttpGet]
        public ActionResult ConfirmRoom(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = rs.GetRoomByID(id);
            if (room == null)
            {
                return HttpNotFound();
            }
           // ViewBag.UserId = new SelectList(uow.UserRepository.GetAll(), "UserId", "Name", room.UserId);
            return View(room);
        }
        [HttpPost]
        public ActionResult ConfirmRoom([Bind(Include = "Id,Name,Price,IsOccupied,CheckInDate,CheckOutDate,UserId")] Room room)
        {
            
            if (ModelState.IsValid)
            {
                room.IsOccupied = true;
                room.UserId = Convert.ToInt32(Session["userID"]);
                //System.Diagnostics.Debug.WriteLine(rs.GetPrice((int)room.Id));
                rs.UpdateRoom(room);
                return RedirectToAction("Index");
            }
            //ViewBag.UserId = new SelectList(db.UserList, "UserId", "Name", room.UserId);
            return View(room);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Session["userID"] != null)
                    {
                        <li>@Html.ActionLink("Logout", "LogOut", "Login")</li>
                        <li>@Html.ActionLink("Logged In as " + Session["userName"], "dummy", null, new { href = "#" })</li>
                        if (Convert.ToBoolean(Session["userIsAdmin"]) == true)
                        {
                            <li>@Html.ActionLink("Rooms", "Index", "Rooms")</li>
                            <li>@Html.ActionLink("Users", "Index", "Users")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Book Room", "Index", "RoomSelect")</li>
                            <li>@Html.ActionLink("My Bookings", "Index", "Bookings")</li>
                        }
                    }
                    else
                    {
                        <li>@Html.ActionLink("LogIn", "Index", "Login")</li>

                    }

                    @if (Session["userID"] == null)
                    {
                        <li>@Html.ActionLink("Book Room", "Index", "RoomSelect")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>